# =============================================================================
# VectorPlane Azure Onboarding - Terraform Module Variables
# =============================================================================
# This module creates an App Registration with Federated Identity Credentials
# (WIF), granting VectorPlane read access to your Azure resources.
# Zero long-lived secrets — authentication uses OIDC JWT signed by VectorPlane.
#
# Supports two onboarding scopes:
#   SUBSCRIPTION       — Single subscription (default)
#   MANAGEMENT_GROUP   — All subscriptions under a management group
# =============================================================================

# -----------------------------------------------------------------------------
# Required Variables (Provided by VectorPlane via pairing exchange)
# -----------------------------------------------------------------------------

variable "external_id" {
  description = "Unique session ID generated by VectorPlane for this onboarding session"
  type        = string

  validation {
    condition     = length(var.external_id) >= 10
    error_message = "external_id must be at least 10 characters (session ID format)"
  }
}

variable "subscription_id" {
  description = "Azure Subscription ID (used for provider init; also the role scope for SUBSCRIPTION onboarding)"
  type        = string

  validation {
    condition     = var.subscription_id == "" || can(regex("^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$", var.subscription_id))
    error_message = "subscription_id must be a valid UUID or empty (for MANAGEMENT_GROUP scope)"
  }
}

variable "webhook_secret" {
  description = "HMAC secret for webhook signature verification (provided by VectorPlane)"
  type        = string
  sensitive   = true

  validation {
    condition     = length(var.webhook_secret) >= 32
    error_message = "webhook_secret must be at least 32 characters for security"
  }
}

# -----------------------------------------------------------------------------
# Scope Configuration
# -----------------------------------------------------------------------------

variable "onboarding_scope" {
  description = "Scope of access: SUBSCRIPTION (single sub) or MANAGEMENT_GROUP (all subs under an MG)"
  type        = string
  default     = "SUBSCRIPTION"

  validation {
    condition     = contains(["SUBSCRIPTION", "MANAGEMENT_GROUP"], var.onboarding_scope)
    error_message = "onboarding_scope must be SUBSCRIPTION or MANAGEMENT_GROUP"
  }
}

variable "management_group_id" {
  description = "Management Group ID (required if onboarding_scope is MANAGEMENT_GROUP)"
  type        = string
  default     = ""
}

# -----------------------------------------------------------------------------
# VectorPlane OIDC Configuration (Provided by pairing exchange)
# -----------------------------------------------------------------------------

variable "vectorplane_callback_url" {
  description = "VectorPlane webhook URL for setup completion notification"
  type        = string
  default     = "https://api.vectorplane.io/api/v1/webhooks/azure-connect"
}

variable "vectorplane_oidc_issuer" {
  description = "VectorPlane OIDC Issuer URL — must match the FIC trust"
  type        = string
  default     = "https://api.vectorplane.io"
}

variable "vectorplane_oidc_subject" {
  description = "VectorPlane OIDC Subject claim (ECS task role ARN)"
  type        = string
}

variable "vectorplane_oidc_audience" {
  description = "OIDC audience claim for Azure token exchange"
  type        = string
  default     = "api://AzureADTokenExchange"
}

# -----------------------------------------------------------------------------
# Resource Naming (Customizable)
# -----------------------------------------------------------------------------

variable "app_display_name" {
  description = "Display name for the Azure AD App Registration"
  type        = string
  default     = "VectorPlane Security"
}
